mode: debug

http:
  host: 0.0.0.0
  port: 8888

ssh:
  host: 0.0.0.0
  port: 2222
  privateKey: --BEGIN PRIVATE KEY-----END PRIVATE KEY-----

guacd:
  host: oneterm-guacd
  port: 4822

mysql:
  host: oneterm-mysql
  port: 3306
  user: root
  password: root

database:
  type: mysql  # alternative: postgres, tidb, tdsql, dm
  host: oneterm-mysql
  port: 3306
  user: root
  password: root
  database: oneterm
  charset: utf8mb4
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600  # seconds
  conn_max_idle_time: 600  # seconds
  ssl_mode: disable

redis:
  addr: oneterm-redis:6379
  password: root

log:
  level: debug
  format: json
  maxSize: 1
  consoleEnable: true

auth:
  acl:
    appId: acl app id
    secretKey: acl app secret key
    url: http://host/api/v1
    resourceNames:
      - key: account
        value: account
      - key: asset
        value: asset
      - key: command
        value: command
      - key: gateway
        value: gateway
      - key: authorization
        value: authorization

secretKey: acl secret key
